-- The "accelerate" step: one statement pulls Snowflake (warehouse) and S3 (lake) into Exasol.
CREATE SCHEMA IF NOT EXISTS DEMO_ACCEL;
CREATE OR REPLACE TABLE DEMO_ACCEL.CUSTOMER_360 AS
SELECT v.C_CUSTKEY, v.C_NAME, v.NATION, v.SEGMENT, v.ORDERS, v.LIFETIME_REVENUE, v.OPEN_ORDER_VALUE,
       v.LAST_ORDER_DATE, d.LINES, d.LATE_LINES, ROUND(100 * d.LATE_LINES / d.LINES, 1) AS PCT_LATE, d.AVG_DAYS_LATE
FROM DEMO_FEDERATED.SF_CUSTOMER_VALUE v
JOIN DEMO_FEDERATED.CUSTOMER_DELIVERY d ON d.C_CUSTKEY = v.C_CUSTKEY;
