-- Run in Snowflake (Snowsight -> Projects -> Workspaces -> + -> SQL file), as ACCOUNTADMIN, with "Run all".
-- Creates: a read-only role, a small warehouse, typed views over the free TPC-H sample, and a service user
-- that logs in with a programmatic access token (PAT). Copy the TOKEN_SECRET from the last result into .env.
USE ROLE ACCOUNTADMIN;

-- If SNOWFLAKE_SAMPLE_DATA is missing in your account:
-- CREATE DATABASE SNOWFLAKE_SAMPLE_DATA FROM SHARE SFC_SAMPLES.SAMPLE_DATA;

CREATE WAREHOUSE IF NOT EXISTS EXASOL_DEMO_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE ROLE IF NOT EXISTS EXASOL_READER;
GRANT USAGE ON WAREHOUSE EXASOL_DEMO_WH TO ROLE EXASOL_READER;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE EXASOL_READER;

-- Typed views: TPC-H keys are NUMBER(38,0). Exasol DECIMAL stops at 36 digits, so the virtual schema would map
-- them to VARCHAR(2000000) (wrong joins, slow transfer). NUMBER(18,0) maps cleanly to DECIMAL(18,0).
CREATE DATABASE IF NOT EXISTS EXASOL_DEMO_ADMIN;
CREATE SCHEMA IF NOT EXISTS EXASOL_DEMO_ADMIN.TPCH;
CREATE OR REPLACE VIEW EXASOL_DEMO_ADMIN.TPCH.CUSTOMER AS SELECT
  C_CUSTKEY::NUMBER(18,0) C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY::NUMBER(18,0) C_NATIONKEY,
  C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE VIEW EXASOL_DEMO_ADMIN.TPCH.ORDERS AS SELECT
  O_ORDERKEY::NUMBER(18,0) O_ORDERKEY, O_CUSTKEY::NUMBER(18,0) O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE,
  O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY::NUMBER(18,0) O_SHIPPRIORITY, O_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
CREATE OR REPLACE VIEW EXASOL_DEMO_ADMIN.TPCH.NATION AS SELECT
  N_NATIONKEY::NUMBER(18,0) N_NATIONKEY, N_NAME, N_REGIONKEY::NUMBER(18,0) N_REGIONKEY, N_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
CREATE OR REPLACE VIEW EXASOL_DEMO_ADMIN.TPCH.REGION AS SELECT
  R_REGIONKEY::NUMBER(18,0) R_REGIONKEY, R_NAME, R_COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
GRANT USAGE ON DATABASE EXASOL_DEMO_ADMIN TO ROLE EXASOL_READER;
GRANT USAGE ON SCHEMA EXASOL_DEMO_ADMIN.TPCH TO ROLE EXASOL_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA EXASOL_DEMO_ADMIN.TPCH TO ROLE EXASOL_READER;

-- Service user: no password, token login only.
CREATE USER IF NOT EXISTS EXASOL_SVC TYPE = SERVICE DEFAULT_ROLE = EXASOL_READER DEFAULT_WAREHOUSE = EXASOL_DEMO_WH;
GRANT ROLE EXASOL_READER TO USER EXASOL_SVC;

-- Service users need a network policy to use a PAT unless an authentication policy relaxes that requirement.
CREATE SCHEMA IF NOT EXISTS EXASOL_DEMO_ADMIN.POLICIES;
CREATE AUTHENTICATION POLICY IF NOT EXISTS EXASOL_DEMO_ADMIN.POLICIES.EXASOL_SVC_AUTH
  PAT_POLICY = (NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED);
ALTER USER EXASOL_SVC SET AUTHENTICATION POLICY EXASOL_DEMO_ADMIN.POLICIES.EXASOL_SVC_AUTH;

-- The token: shown ONCE in the TOKEN_SECRET column. Put it in .env as SNOWFLAKE_PAT.
-- To recreate it later: ALTER USER EXASOL_SVC REMOVE PROGRAMMATIC ACCESS TOKEN EXASOL_DEMO; then run this again.
ALTER USER EXASOL_SVC ADD PROGRAMMATIC ACCESS TOKEN EXASOL_DEMO
  ROLE_RESTRICTION = 'EXASOL_READER' DAYS_TO_EXPIRY = 30 COMMENT = 'Exasol virtual schema demo';
